### ISSUE TITLE
Suggestion and bug about tree view

### ISSUE THREAD

**Issue by Amanoki** [JacquesGariepy/out-of-code-insights#3]
Hi, thanks for this fantastic extension. I've been looking for an extension like this and it's the one I've tried that can actually follow and stick to the code when its line number changes. Very cool!

For now I'd like to leave some feedback for Tree View:
(VS Code version: 1.95.3; Extension version: 1.0.5)
1. Suggestion:
Currently the `Delete` and `Edit` button take up a lot of width and can be easily mis-clicked when the sidebar is narrow. It would be nice if they could be shown as icons, so they save space and be more consistent with the other parts of VS Code UI, like this:
(the image on the right is from VS Code's Search panel)

![ss](https://github.com/user-attachments/assets/140a11ab-306a-4c3e-8227-74a668439cc7)

2. Bug?:
Currently the `Delete` and `Edit` on the Tree View are targeting the line the cursor is on instead of the actual note item clicked in tree view. If there is no notes under the cursor, it says `No annotation found on this line`, and if the cursor is on the line of a different note, it deletes or edits that note instead of the clicked note in tree view. I assume this is a bug, as one might usually expect the actions on the tree view should work for the corresponding item in the view.
3. Feature that I personally would love:
`Move Up/Down` buttons in the tree view. Nice to have, if the buttons are changed to icons as mentioned in point 1 and more space is available.
(Btw it's mentioned in the description that `Move Up/Down` should be in the context menu, but I can't seem to find them)
4. Another feature request:
An option for tree view to show notes from all files or only from the current file. Perhaps a filter icon on the panel or a customizable option in the extension settings?

Thanks for your consideration. I look forward to seeing this extension get better and better!

**Comment by JacquesGariepy** [comment]
I encourage you to upgrade to version 1.0.7, which I believe will meet your expectations.  

For point 1, I encourage you to upgrade to the latest version, 1.0.7, where I have updated the display.  

For point 2, this is a bug I believe I’ve fixed in version 1.0.7 as well. You need to select the note and then edit it. I haven’t yet added the functionality to allow editing only while hovering over the note, but that should be coming soon. If you press CTRL + ALT + S, you’ll find a control panel, which is more accessible via version 1.0.7 as well (Show Annotations Panel with the eye icon).  

For point 3, right-clicking on the note displays a menu, and it is possible to move up or down. However, I will add up and down icons directly in the tree view; they are already available in the View Panel.  

For point 4, again in version 1.0.7, there is a filter in the Panel View, a search function in the tree view, and options available in the context menus.  

Your feedback is truly appreciated. Thank you!
