### ISSUE TITLE
"enable the AI Suggested Annotation?" popup ignores answers

### ISSUE THREAD

**Issue by tyler36** [JacquesGariepy/out-of-code-insights#9]
Thank you for the update regarding #5. Unforunetly, the option does not appear to work for me.

After updating to `1.0.9`, I get a popup that says:

"Do you want to enable the AI Suggested Annotation feature?"

If I click "No",  I get a popup asking for my OpenAI key. 
My settings file now contains `"annotation.enableAiSuggest": false,`, but I receieve the popup to "enable the AI ...?", and "OpenAI key" on reload.

Disabling the extention causes the both popups to disappear.

Out-of-code: `1.0.9`
VSCode : `1.96.0`
OS: WSL (Ubuntu) via Win11

**Comment by JacquesGariepy** [comment]
Hi there,

Thank you for reporting this issue and providing detailed steps to reproduce it. We’ve identified the cause of the problem and have implemented a fix. The updated version (1.0.10) has just been published to the marketplace.

Please update to version 1.0.10 and let us know if the issue is resolved. If you continue to experience problems, feel free to reopen this issue or create a new one with additional details.

Thanks again for your feedback and patience!

**Comment by tyler36** [comment]
Thank you for the quick response.

I can confirm that `1.0.10` resolves the issue in my original description above.
